Allow more control over allowing includes
JSONAPI-Resources/jsonapi-resources pull request #1096
Opened 2017-08-08 12:51 UTC by lgebhardt

Deprecates and replaces the `allow_include` config option

Replaces `allow_includes` with `default_allow_include_to_one` and `default_allow_include_to_many` configuration options.
Adds support for `allow_include` option on Relationships to override the config settings.

Purpose:
- Includes without pagination allows potentially resource intensive requests.
- Pagination of includes is a non-trivial problem to solve efficiently with SQL databases
- By allowing includes defaults to be set for to_one and to_many relationship types separately includes for the riskier to_many relationships can be disabled by default, while still allowing them on specific relationships if desired.

2018-08-21 16:40 UTC, joegaudet commented on lib/jsonapi/relationship.rb
> +      def allow_include?
This is awesome, would be cool to have the context passed in, similarly to fetchable_fields useful to remove some depending on the current user.

2018-10-01 18:03 UTC, lgebhardt commented on lib/jsonapi/relationship.rb
> +      def allow_include?
@joegaudet Good idea

2018-10-01 18:03 UTC, lgebhardt commented
Updated for @joegaudet so you can now provide a boolean, a callable name, or a lambda for `allow_include`. Context is passed to the callable and lambda.

2018-10-30 17:45 UTC, dgeb requested changes
Looks pretty good. Needs one simple fix. I'd also feel more comfortable if the recursion logic in `check_include` were tested.

2018-10-30 17:45 UTC, dgeb commented on lib/jsonapi/relationship.rb
> +                     JSONAPI.configuration.default_allow_include_to_one
should be `JSONAPI.configuration.default_allow_include_to_many`

2018-10-31 13:40 UTC, dgeb approved these changes

2018-10-31 14:50 UTC, merged