Default to more restrictive backtrace configuration
JSONAPI-Resources/jsonapi-resources pull request #1204
Opened 2018-12-26 19:44 UTC by arcreative

Needed to avoid exposing stack traces in non-production but non-development environments (e.g. "staging")

Fixes #1203

### All Submissions:

- [X] I've checked to ensure there aren't other open [Pull Requests](https://github.com/cerebris/jsonapi-resources/pulls) for the same update/change.
- [ ] I've submitted a [ticket](https://github.com/cerebris/jsonapi-resources/issues) for my issue if one did not already exist.
- [ ] My submission passes all tests. (Please run the full test suite locally to cut down on noise from travis failures.)
- [ ] I've used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message or the description.
- [ ] I've added/updated tests for this change.

### New Feature Submissions:

- [ ] I've submitted an issue that describes this feature, and received the go ahead from the maintainers.
- [ ] My submission includes new tests.
- [ ] My submission maintains compliance with [JSON:API](http://jsonapi.org/).

### Bug fixes and Changes to Core Features:

- [ ] I've included an explanation of what the changes do and why I'd like you to include them.
- [ ] I've provided test(s) that fails without the change.

### Test Plan:

### Reviewer Checklist:
- [ ] Maintains compliance with JSON:API
- [ ] Adequate test coverage exists to prevent regressions

2018-12-28 08:38 UTC, senid231 requested changes

2018-12-28 08:38 UTC, senid231 commented on lib/jsonapi/configuration.rb
> +      self.include_backtraces_in_errors = (Rails.env.development? or Rails.env.test?)
please use `||` instead of `or`

https://github.com/rubocop-hq/ruby-style-guide#no-and-or-or

2018-12-28 08:38 UTC, senid231 commented on lib/jsonapi/configuration.rb
> +      self.include_application_backtraces_in_errors = (Rails.env.development? or Rails.env.test?)
please use || instead of or

https://github.com/rubocop-hq/ruby-style-guide#no-and-or-or

2018-12-29 00:18 UTC, arcreative commented on lib/jsonapi/configuration.rb
> +      self.include_application_backtraces_in_errors = (Rails.env.development? or Rails.env.test?)
@senid231 Done, thanks

2018-12-30 09:00 UTC, senid231 approved these changes

2019-01-03 19:48 UTC, merged

2019-01-03 19:48 UTC, lgebhardt commented
@arcreative Thanks!