Fix creating polymorphic has many relations
JSONAPI-Resources/jsonapi-resources pull request #1231
Opened 2019-03-15 16:33 UTC by st0012

This is a continuation of #1217, which fixes its failing tests (thanks for @saravanak's hard work!). 

The cause of #1217's failure is data mutation between test cases: the integration test's post request creates a new record, and it fails other tests (under certain execution order). So my additional commit is to keep the database clean (with [database_cleaner](https://github.com/DatabaseCleaner/database_cleaner) before/after each integration test suite.

### All Submissions:

- [x] I've checked to ensure there aren't other open [Pull Requests](https://github.com/cerebris/jsonapi-resources/pulls) for the same update/change.
- [ ] I've submitted a [ticket](https://github.com/cerebris/jsonapi-resources/issues) for my issue if one did not already exist.
- [x] My submission passes all tests. (Please run the full test suite locally to cut down on noise from travis failures.)
- [ ] I've used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message or the description.
- [x] I've added/updated tests for this change.

### New Feature Submissions:

- [ ] I've submitted an issue that describes this feature, and received the go ahead from the maintainers.
- [ ] My submission includes new tests.
- [ ] My submission maintains compliance with [JSON:API](http://jsonapi.org/).

### Bug fixes and Changes to Core Features:

- [x] I've included an explanation of what the changes do and why I'd like you to include them.
- [x] I've provided test(s) that fails without the change.

### Test Plan:

### Reviewer Checklist:
- [ ] Maintains compliance with JSON:API
- [ ] Adequate test coverage exists to prevent regressions

2019-03-17 19:08 UTC, lgebhardt requested changes
Thanks @saravanak and @st0012 This is a good start, but it's not thoroughly tested and further work is needed downstream in the Resource for creating the relationship links.

2019-03-17 19:08 UTC, lgebhardt commented on lib/jsonapi/request_parser.rb
>            add_result.call relationship_resource.verify_keys(keys, @context)
This is going to call `add_result` for each type, which will overwrite the previous type. In addition the type information will be lost. Look at line 503 for how `parse_to_one_relationship` handles this. Then `Resource._replace_fields` will need some changes.

2019-03-17 19:08 UTC, lgebhardt commented on test/integration/requests/request_test.rb
> +
Let's test cases where multiple vehicles are provided. Tests should include mismatches of types, such as 
```
'relationships' => {
             'vehicles' => {'data' => [{'type' => 'car', 'id' => '1'}, {'type' => 'car', 'id' => '2'}]}, #vehicle 2 is actually a boat
           }
```

Test should probably be repeated for updates, though as of now they should go through the same path.

2019-03-17 19:08 UTC, lgebhardt commented on test/integration/requests/request_test.rb
> +    assert_jsonapi_response 201
Ensure that the changes went through as requested. The code will currently fail if mixed vehicle types are provided.

2019-03-18 10:16 UTC, st0012 commented on lib/jsonapi/resource.rb
> +        relationship_klass = relationship_resource_klass.model_hint.classify.safe_constantize
@lgebhardt have one question here: when `relationship_resource_klass` is a subclass resource (like `CarResource`), its `_model_class` still returns `Vehicle` instead of `Car`. Is this intentional? Is there an easier way for me to get `Car` from `CarResource`?

2019-03-18 10:16 UTC, st0012 commented on lib/jsonapi/resource.rb
> +          fail JSONAPI::Exceptions::RecordNotFound.new(relationship_key_values[:ids])
The reason to raise RecordNotFound instead of TypeMismatch is that type mismatch requires 2 conditions:
      - the id can't be used to find any record in current subclass (Car)
      - but in the meantime, it does exists for the superclass (Vehicle)
And this means we need to perform additional query to prove the second condition, which is kind of a waste.

2019-03-18 12:44 UTC, lgebhardt commented on lib/jsonapi/resource.rb
> +          fail JSONAPI::Exceptions::RecordNotFound.new(relationship_key_values[:ids])
I tend to agree it's kind of a waste, but from a JSON API perspective it's not known that the backing table is sharing a common set of IDs. So there really isn't a Car with id 2 so the system should raise an error.

2019-03-18 12:48 UTC, lgebhardt commented on lib/jsonapi/resource.rb
> +          fail JSONAPI::Exceptions::RecordNotFound.new(relationship_key_values[:ids])
Let's use `find_by_keys`, like https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L251. That way any overrides will get applied. This might be the case if people are doing permission checking for these related resources.

2019-03-18 13:51 UTC, lgebhardt commented on lib/jsonapi/resource.rb
> +        relationship_klass = relationship_resource_klass.model_hint.classify.safe_constantize
This wasn't intentional. It's happening because the CarResource inherits from VehicleResource and the model_name is inherited. Changing this will break a lot of the tests and probably production code.

So as a workaround I propose we add model_name calls to CarResource and BoatResource:
```ruby
class CarResource < VehicleResource
  model_name 'Car'
  attributes :drive_layout
end

class BoatResource < VehicleResource
  model_name 'Boat'
  attributes :length_at_water_line
end
```

and clear `@model_class` when the `model_name` is set in `Resource. model_name`:
```ruby

     def model_name(model, options = {})
        @model_class = nil #this is new
        @_model_name = model.to_sym

        model_hint(model: @_model_name, resource: self) unless options[:add_model_hint] == false

        rebuild_relationships(_relationships)
      end
```

That should allow you to use `_model_class` instead.

I'll think about a better solution as I don't like needing to specify the `model_name`.

2019-03-18 14:14 UTC, st0012 commented on lib/jsonapi/resource.rb
> +          .records
@lgebhardt for supporting customizations, I think using `records` is enough. Use `find_by_keys` will also run includes for this query, which is unncessary.

2019-03-19 03:14 UTC, st0012 commented
@lgebhardt added tests for update, is there anything missing for merging?

2019-03-19 13:55 UTC, lgebhardt requested changes
@st0012 There are a few test failures masked by using `assert` instead of `assert_equal`.

2019-03-19 13:55 UTC, lgebhardt commented on lib/jsonapi/resource.rb
> +          .records
I missed this earlier: `records` needs to be called as `records(options)`

2019-03-19 13:55 UTC, lgebhardt commented on lib/jsonapi/resource.rb
> +        missed_ids = ids - related_records.map(&:id)
We need to account for alternate primary keys, and I think we can skip creating the models so pluck will save a few cycles.
```ruby
missed_ids = ids - related_records.pluck(relationship_resource_klass._primary_key)
```

2019-03-19 13:55 UTC, lgebhardt commented on test/integration/requests/request_test.rb
> +    assert 2, person.vehicles.count
These asserts should be `assert_equal`. Once fixed this test is failing with only the last vehicle type being created.

2019-03-19 15:36 UTC, st0012 commented on test/integration/requests/request_test.rb
> +    assert 2, person.vehicles.count
ah sorry 😅

2019-03-19 15:37 UTC, st0012 commented on lib/jsonapi/resource.rb
> +        missed_ids = ids - related_records.map(&:id)
👍

2019-03-19 15:39 UTC, st0012 commented
@lgebhardt all updated!

2019-03-19 18:57 UTC, lgebhardt commented
@st0012 Thanks for working on this. I squashed your changes and pushed them to release-0-9

2019-03-19 18:57 UTC, closed without merging