Feature Custom Actions for resources
JSONAPI-Resources/jsonapi-resources pull request #928
Opened 2016-12-14 14:20 UTC by Exelord

Hi,
I just moved our extension for custom actions to my fork. I know this behavior is not documented in JSONAPI standard but this will probably come:
 - https://github.com/json-api/json-api/issues/745
 - https://github.com/json-api/json-api/issues/684

So, I built a solution for that which can be later on extended by the up-coming feature.

## TODO

- [ ] Tests
- [ ] Required parameters
- [ ] Configurable behaviours

## Documentation
To start using it add a `custom_action` to the resource, eg:
```ruby
class Api::V1::ProjectResource < JSONAPI::Resource
  custom_action :publish, type: :post

  def publish(data)
    # in `data` you can find passed arguments
    DistributeService.publish(@model, data[:publisher_id]) # The `@model` is a `Project` instance
  end
end
```

Make a request:
```
// POST { "data": { "publisher-id": "4" } }
https://api.app.com/projects/:id/publish
```
And you will receive serialized object returned from the service.
If the service returns `nil` or model without resource in the response will be a default resource (in this example `@model` ie. `Project` instance)

The response object, by default, will be returned with all available includes.

You can also customize `custom_action` with the following options:
- `type`:  [:get, :post, :patch, :put] 
- `apply`: You can pass a `Proc` if you dont want to use method:
```ruby
custom_action :publish, type: :post, apply: (lambda do |model, context, data|
    # your logic
  end)
```  
- `method`: If you wish, you can change method name to eg: `publish_this_project`

2016-12-20 18:43 UTC, Exelord commented
@lgebhardt @barelyknown could you give me some feedback and remarks?
Should I still continue work on it or just drop the idea?

2016-12-20 18:48 UTC, lgebhardt commented
@Exelord Sorry for the delay. I'll look it over soon.

2016-12-22 00:44 UTC, nagirrab commented
In case it's useful to the discussion, I built something similar, fully tested and working, see: 

https://github.com/nagirrab/jsonapi-resources/commit/72bd6359f3628c4d71660221dec73c083e9519b6

It has many of the same features but includes collection level actions as well as instance level. Instead of specifying a single method, you create another nested resource class to validate the parameters sent to the custom action the same way a PUT/POST call would be validated.

In the end, I refactored the offending methods into separate resources because I wasn't fully satisfied with the mechanic, but happy to resurrect it or help on someone else's version if the wind's blowing that way.

Looking at the mentioned spec discussion, it seems that it's more likely @Exelord's solution will fit the bill.

2017-03-13 03:13 UTC, jufemaiz commented
Would love to know if this is something that will progress?

2017-03-13 12:24 UTC, Exelord commented
It's still waiting for @lgebhardt comments.

2017-03-23 04:31 UTC, jufemaiz commented
Did @lgebhardt's comments disappear then?

2017-03-23 07:23 UTC, Exelord commented
Yep, @jufemaiz :/ Here is what he wrote:
> @Exelord I have some concerns about putting the new actions on the resources. I feel it's more consistent to place the implementation on the processors. However I recognize that the parsing of the request for a new action will be awkward since we still haven't given a decent way to extend the RequestParser.
I hope to have some time soon to look into this.

2017-03-23 16:17 UTC, lgebhardt commented
Sorry, I'm not sure why the comment disappeared, probably when I cancelled the review (just a few line comments), but that seems wrong. Glad you kept the email.

I've put #1010 together as a place to discuss changes so we can get your custom actions finished and not lock us into an architecture I'm not happy with.

Thanks for your patience with this.

2017-03-24 21:08 UTC, Exelord commented
Great, so as I understand, we can continue work on it and then change the architecture, is that correct?

Together with my team, we test it out on production since September or maybe longer. According to that, I have a few proposal that we can discuss.

## Custom actions in controllers
I suggest splitting `custom_actions` method in controllers to separate methods, eg: `invite`, `login`, `search` etc... or add a prefix or suffix to them to pretend accidental overwriting.

We have to think about `resource actions` and `models actions`. They can have the same name, so in that case we should really consider adding a prefix or suffix.

Spliting the action can help with testing, performance measurement tools, overwriting (if needed) and will increase readability of controller API (the actions logic will be explicit)

## Routes
I was thinking about covering a case for `resource actions`. In my opinion to declare them in `routes` will be sth like it was for my proposal:
```rb
jsonapi_resources :projects do
  jsonapi_custom_actions
end
``` 
In my opionin `jsonapi_custom_actions` method should generate a routes for `models actions` and also for `resource actions`. What do you think? Or we should force `jsonapi_resources` method to handle that by default?

_______
I will add more ideas and concerns after the architecure of this API's.

2017-04-21 14:24 UTC, Exelord commented
Hi @lgebhardt,
Together with @poslinskiNet we:
- upgraded the PR to the latest version
- updated the code
- added the code documentation
- updated PR documentation
- added a support for custom actions on collection level

We are also in progress with tests (almost at the end - they will show up in a few days)
Feedback is welcome... We spend a lot of time on this so we hope it will follow us to some point.

2017-04-22 15:59 UTC, PoslinskiNet commented
@Exelord @lgebhardt I've pushed the specs and some improvements. I hope it will speed up the integration of the code. If you have any remarks, just let me know. Enjoy your weekend 👍

2017-05-04 10:25 UTC, chrism commented
This is really brilliant and something that would be incredibly useful on one of my projects.

Thank you for all the hard work on it.

Is there any way to help get this merged and released?

Thanks!

2017-05-04 11:27 UTC, Exelord commented
Maybe @barelyknown could help :)

2017-05-04 14:30 UTC, lgebhardt commented
This isn't following the flow of the existing actions. For example `setup_custom_actions_action` is calling the `apply` method for the action. `apply` shouldn't be called until the operation is being processed. The setup should create an `Operation` object which will then be processed by the `Processor`. Using a custom `Processor` and moving the logic from the `apply` callable would fit better with the existing architecture.

I propose that we allow the creation of custom `RequestParser`s for a controller (or set by Resource). That will create a custom `Operation` which is processed by a custom `Processor`.  The response would be handled with a custom `OperationResult`, if needed, which handles the conversion to JSON.

The new piece needed would be the new `RequestParser` support. I think the existing rails route methods would work for setting up the routes. This is a much smaller set of changes and would leverage the existing framework.

Custom actions need to be able to set whether they are transactional. Now that's done by method name, but it might be better to handle it on the `Operation`.

Support for a custom media type for extension requests would be nice, but probably not necessary.

2017-05-09 10:07 UTC, chrism commented
Maybe this isn't the appropriate place for this, but I've been unable to find any information elsewhere and it relates directly so I'd just like to ask.

Without a solution such as this what is the current best practice for working with a specific non-RESTful API endpoint?

I've been adding more conditional logic into the update method in a controller, but it feels like a really bad approach and is very hard to test.

2017-05-09 12:37 UTC, PoslinskiNet commented
Hello @chrism,

In fact, the idea of custom actions addresses your case and gives you some flexibility over responses (it can return as response any type of resource/resources - it is up to you). It also simplifies the logic, because you don't have to have some conditionals - instead you can have multiple custom action endpoints which contain for example service object that can be easily testable.

2017-05-09 14:53 UTC, chrism commented
Hi @PoslinskiNet,

Thanks very much for responding. Yes absolutely, that is what I understood by the idea and would be absolutely perfect for my use cases, like you have kindly explained.

I was wondering though, until this PR is merged to the satisfaction of @lgebhardt is there a reasonable way to do this with the current release that is more 'best practice' than my 'hack'?

2017-08-03 16:49 UTC, PoslinskiNet commented
Would be nice to have it some day integrated to the main repository. Maybe someone is open for taking specs that are already in-place and do some adjustments to the implementation so It can be merged eventually by the gem owner (we can help, but we don't have enough time to rewrite it from scratch)?

Keep in mind that It doesn't break the current version of **jsonapi-resources**, it just extends it with pretty cool behaviour 😈 .

2019-01-31 13:44 UTC, ArneZsng requested changes
As we are using this PR in one of our forks, I just wanted to share an update on the code we needed to incorporate to make it work for us.

2019-01-31 13:44 UTC, ArneZsng commented on lib/jsonapi/custom_actions/extensions/processor.rb
> +    end
Since the internal API of JSONAPI::Resources has changed quite a bit since this PR was opened, I think this method needs a little update.

One proposal:
```suggestion
        # Processing custom actions results for single model
    # It will handle action result if returns one single model
    #
    # @return [ResourceSetOperationResult]
    def custom_actions_instance
      resource = resource_klass.resource_for(params[:result], context)

      include_directives = params[:include_directives]
      fields = params[:fields]
      serializer = params[:serializer]

      find_options = {
        context: context,
        fields: fields,
        filters: { resource_klass._primary_key => resource.id }
      }

      resource_set = find_resource_set(resource_klass,
                                       include_directives,
                                       serializer,
                                       find_options)

      JSONAPI::ResourceSetOperationResult.new(:ok, resource_set, result_options)
    rescue
      JSONAPI::OperationResult.new(:accepted, result_options)
    end
```

2019-01-31 13:44 UTC, ArneZsng commented on lib/jsonapi/custom_actions/extensions/processor.rb
> +    end
Same as above, this can use an update.

```suggestion
        # Processing custom actions results for many models
    # It will handle action result if returns array or ActiveRecord::Relation
    #
    # @return [ResourceSetOperationResult]
    def custom_actions_collection
      resources = resource_klass.resources_for(params[:results], context)

      include_directives = params[:include_directives]
      fields = params[:fields]
      serializer = params[:serializer]

      find_options = {
        context: context,
        fields: fields,
        filters: { resource_klass._primary_key => resources.map(&:id) }
      }

      resource_set = find_resource_set(resource_klass,
                                       include_directives,
                                       serializer,
                                       find_options)

      JSONAPI::ResourceSetOperationResult.new(:ok, resource_set, result_options)
    rescue
      JSONAPI::OperationResult.new(:accepted, result_options)
    end
```

2022-12-17 00:38 UTC, closed without merging